//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class onlinetestingEntities3 : DbContext
    {
        public onlinetestingEntities3()
            : base("name=onlinetestingEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<mark> marks { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<test> tests { get; set; }
        public DbSet<testData> testDatas { get; set; }
        public DbSet<userdata> userdatas { get; set; }
    }
}
