//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService5
{
    using System;
    using System.Collections.Generic;
    
    public partial class testData
    {
        public testData()
        {
            this.marks = new HashSet<mark>();
            this.tests = new HashSet<test>();
        }
    
        public int test_id { get; set; }
        public int user_id { get; set; }
        public string testName { get; set; }
        public string testSubject { get; set; }
        public string testTime { get; set; }
        public string testMaxMarks { get; set; }
        public string testDetails { get; set; }
    
        public virtual ICollection<mark> marks { get; set; }
        public virtual ICollection<test> tests { get; set; }
        public virtual userdata userdata { get; set; }
    }
}
