//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService5
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        public int id { get; set; }
        public int test_id { get; set; }
        public string question { get; set; }
        public string option1 { get; set; }
        public string option2 { get; set; }
        public string option3 { get; set; }
        public string option4 { get; set; }
        public string right_ans { get; set; }
    
        public virtual testData testData { get; set; }
    }
}
